Normalize workflow compatibility for attack preparation.

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -1,4 +1,4 @@
-on:
+'on':
   workflow_call:
     inputs:
       e2e-labels:
@@ -11,119 +11,130 @@ on:
         required: true
 jobs:
   e2e-test:
-    runs-on:
-      - self-hosted-nutanix-docker-medium
+    runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          ref: "${{ github.event.pull_request.head.sha }}"
+    - name: Checkout
+      uses: actions/checkout@v4
+      with:
+        ref: ${{ github.event.pull_request.head.sha }}
+    - name: Install Nix on self-hosted ARC runners
+      uses: DeterminateSystems/nix-installer-action@v20
+      with:
+        github-token: ${{ secrets.GITHUB_TOKEN }}
+        logger: pretty
+        extra-conf: experimental-features = ca-derivations fetch-closure
+    - name: Install devbox
+      uses: jetify-com/devbox-install-action@v0.14.0
+      with:
+        enable-cache: 'false'
+        skip-nix-installation: 'true'
+    - uses: actions/cache@v4
+      with:
+        path: '~/.cache/golangci-lint
 
-      # Install nix using DeterminateSystems/nix-installer-action if running on ARC runners
-      # This can be removed once jetify-com/devbox-install-action has a release that includes
-      # at least `DeterminateSystems/nix-installer-action@v19` which includes the fix in
-      # https://github.com/DeterminateSystems/nix-installer-action/issues/68
-      - name: Install Nix on self-hosted ARC runners
-        uses: DeterminateSystems/nix-installer-action@v20
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          logger: pretty
-          extra-conf: experimental-features = ca-derivations fetch-closure
+          ~/.cache/go-build
 
-      - name: Install devbox
-        uses: jetify-com/devbox-install-action@v0.14.0
-        with:
-          enable-cache: "false"
-          skip-nix-installation: "true"
+          ~/go/pkg/mod
 
-      - uses: actions/cache@v4
-        with:
-          path: |
-            ~/.cache/golangci-lint
-            ~/.cache/go-build
-            ~/go/pkg/mod
-          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-          restore-keys: |
-            ${{ runner.os }}-go-
+          '
+        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+        restore-keys: '${{ runner.os }}-go-
 
-      - name: Set Prism Element Cluster parameters
-        id: pe-params
-        run: |
-          if [[ "${{ inputs.e2e-labels }}" == "gpu" ]]; then
-            echo "NUTANIX_PRISM_ELEMENT_CLUSTER_NAME=${{ vars.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME_WITH_GPU }}" >> "${GITHUB_OUTPUT}"
-            echo "NUTANIX_SUBNET_NAME=${{ vars.NUTANIX_SUBNET_NAME_WITH_GPU }}" >> "${GITHUB_OUTPUT}"
-            echo "CONTROL_PLANE_ENDPOINT_RANGE_START=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_START_WITH_GPU }}" >> "${GITHUB_OUTPUT}"
-            echo "CONTROL_PLANE_ENDPOINT_RANGE_END=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_END_WITH_GPU }}" >> "${GITHUB_OUTPUT}"
-          else
-            echo "NUTANIX_PRISM_ELEMENT_CLUSTER_NAME=${{ vars.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME }}" >> "${GITHUB_OUTPUT}"
-            echo "NUTANIX_SUBNET_NAME=${{ vars.NUTANIX_SUBNET_NAME }}" >> "${GITHUB_OUTPUT}"
-            echo "CONTROL_PLANE_ENDPOINT_RANGE_START=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_START }}" >> "${GITHUB_OUTPUT}"
-            echo "CONTROL_PLANE_ENDPOINT_RANGE_END=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_END }}" >> "${GITHUB_OUTPUT}"
-          fi
+          '
+    - name: Set Prism Element Cluster parameters
+      id: pe-params
+      run: "if [[ \"${{ inputs.e2e-labels }}\" == \"gpu\" ]]; then\n  echo \"NUTANIX_PRISM_ELEMENT_CLUSTER_NAME=${{\
+        \ vars.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME_WITH_GPU }}\" >> \"${GITHUB_OUTPUT}\"\
+        \n  echo \"NUTANIX_SUBNET_NAME=${{ vars.NUTANIX_SUBNET_NAME_WITH_GPU }}\"\
+        \ >> \"${GITHUB_OUTPUT}\"\n  echo \"CONTROL_PLANE_ENDPOINT_RANGE_START=${{\
+        \ vars.CONTROL_PLANE_ENDPOINT_RANGE_START_WITH_GPU }}\" >> \"${GITHUB_OUTPUT}\"\
+        \n  echo \"CONTROL_PLANE_ENDPOINT_RANGE_END=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_END_WITH_GPU\
+        \ }}\" >> \"${GITHUB_OUTPUT}\"\nelse\n  echo \"NUTANIX_PRISM_ELEMENT_CLUSTER_NAME=${{\
+        \ vars.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME }}\" >> \"${GITHUB_OUTPUT}\"\n \
+        \ echo \"NUTANIX_SUBNET_NAME=${{ vars.NUTANIX_SUBNET_NAME }}\" >> \"${GITHUB_OUTPUT}\"\
+        \n  echo \"CONTROL_PLANE_ENDPOINT_RANGE_START=${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_START\
+        \ }}\" >> \"${GITHUB_OUTPUT}\"\n  echo \"CONTROL_PLANE_ENDPOINT_RANGE_END=${{\
+        \ vars.CONTROL_PLANE_ENDPOINT_RANGE_END }}\" >> \"${GITHUB_OUTPUT}\"\nfi\n"
+    - name: Get Control Plane endpoint IP
+      id: get-control-plane-endpoint-ip
+      run: 'export CONTROL_PLANE_ENDPOINT_RANGE_START="${{ steps.pe-params.outputs.CONTROL_PLANE_ENDPOINT_RANGE_START
+        }}"
 
-      - name: Get Control Plane endpoint IP
-        id: get-control-plane-endpoint-ip
-        run: |
-          export CONTROL_PLANE_ENDPOINT_RANGE_START="${{ steps.pe-params.outputs.CONTROL_PLANE_ENDPOINT_RANGE_START }}"
-          export CONTROL_PLANE_ENDPOINT_RANGE_END="${{ steps.pe-params.outputs.CONTROL_PLANE_ENDPOINT_RANGE_END }}"
-          control_plane_endpoint_ip="$(devbox run -- make nutanix-cp-endpoint-ip)"
-          echo "control_plane_endpoint_ip=${control_plane_endpoint_ip}" >> "${GITHUB_OUTPUT}"
+        export CONTROL_PLANE_ENDPOINT_RANGE_END="${{ steps.pe-params.outputs.CONTROL_PLANE_ENDPOINT_RANGE_END
+        }}"
 
-      - name: Check Control Plane endpoint IP
-        run: |
-          if [[ -z "${{ steps.get-control-plane-endpoint-ip.outputs.control_plane_endpoint_ip }}" ]]; then
-            echo "control_plane_endpoint_ip is empty; cannot proceed with e2e tests"
-            exit 1
-          fi
+        control_plane_endpoint_ip="$(devbox run -- make nutanix-cp-endpoint-ip)"
 
-      - name: Get Control Plane endpoint IP for clusterctl upgrade test
-        id: get-control-plane-endpoint-ip-clusterctl-upgrade
-        run: |
-          export CONTROL_PLANE_ENDPOINT_RANGE_START="${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_START }}"
-          export CONTROL_PLANE_ENDPOINT_RANGE_END="${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_END }}"
-          control_plane_endpoint_ip="$(devbox run -- make nutanix-cp-endpoint-ip)"
-          echo "control_plane_endpoint_ip_clusterctl_upgrade=${control_plane_endpoint_ip}" >> "${GITHUB_OUTPUT}"
+        echo "control_plane_endpoint_ip=${control_plane_endpoint_ip}" >> "${GITHUB_OUTPUT}"
 
-      - name: Check Control Plane endpoint IP for clusterctl upgrade
-        run: |
-          if [[ -z "${{ steps.get-control-plane-endpoint-ip-clusterctl-upgrade.outputs.control_plane_endpoint_ip_clusterctl_upgrade }}" ]]; then
-            echo "control_plane_endpoint_ip_clusterctl_upgrade is empty; cannot proceed with e2e tests"
-            exit 1
-          fi
+        '
+    - name: Check Control Plane endpoint IP
+      run: "if [[ -z \"${{ steps.get-control-plane-endpoint-ip.outputs.control_plane_endpoint_ip\
+        \ }}\" ]]; then\n  echo \"control_plane_endpoint_ip is empty; cannot proceed\
+        \ with e2e tests\"\n  exit 1\nfi\n"
+    - name: Get Control Plane endpoint IP for clusterctl upgrade test
+      id: get-control-plane-endpoint-ip-clusterctl-upgrade
+      run: 'export CONTROL_PLANE_ENDPOINT_RANGE_START="${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_START
+        }}"
 
-      - name: Login to Internal Container Registry
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ secrets.LOCAL_IMAGE_REGISTRY }}
-          username: ${{ secrets.LOCAL_IMAGE_REGISTRY_USERNAME }}
-          password: ${{ secrets.LOCAL_IMAGE_REGISTRY_TOKEN }}
+        export CONTROL_PLANE_ENDPOINT_RANGE_END="${{ vars.CONTROL_PLANE_ENDPOINT_RANGE_END
+        }}"
 
-      - name: Test build
-        run: devbox run -- make ${{ inputs.make-target }} LABEL_FILTERS='${{ inputs.e2e-labels }}'
-        env:
-          NUTANIX_USER: ${{ secrets.NUTANIX_USER }}
-          NUTANIX_PASSWORD: ${{ secrets.NUTANIX_PASSWORD }}
-          NUTANIX_ENDPOINT: ${{ secrets.NUTANIX_ENDPOINT }}
-          NUTANIX_GPU_PASSTHROUGH_NAME: '${{ vars.NUTANIX_GPU_PASSTHROUGH_NAME }}'
-          NUTANIX_GPU_VIRTUAL_NAME: '${{ vars.NUTANIX_GPU_VIRTUAL_NAME }}'
-          NUTANIX_PRISM_ELEMENT_CLUSTER_IP: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_IP }}
-          NUTANIX_PRISM_ELEMENT_CLUSTER_USERNAME: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_USERNAME }}
-          NUTANIX_PRISM_ELEMENT_CLUSTER_PASSWORD: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_PASSWORD }}
-          LOCAL_IMAGE_REGISTRY: ${{ secrets.LOCAL_IMAGE_REGISTRY }}
-          WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
-          WEBHOOK_CERT: ${{ secrets.WEBHOOK_CERT }}
-          WEBHOOK_CA: ${{ secrets.WEBHOOK_CA }}
-          NUTANIX_SSH_AUTHORIZED_KEY: ${{ secrets.NUTANIX_SSH_AUTHORIZED_KEY }}
-          NUTANIX_PRISM_ELEMENT_CLUSTER_NAME: ${{ steps.pe-params.outputs.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME }}
-          NUTANIX_SUBNET_NAME: ${{ steps.pe-params.outputs.NUTANIX_SUBNET_NAME }}
-          NUTANIX_ADDITIONAL_SUBNET_NAME: ${{ vars.NUTANIX_ADDITIONAL_SUBNET_NAME }}
-          NUTANIX_PROJECT_NAME: ${{ vars.NUTANIX_PROJECT_NAME }}
-          CONTROL_PLANE_ENDPOINT_IP: ${{ steps.get-control-plane-endpoint-ip.outputs.control_plane_endpoint_ip }}
-          CONTROL_PLANE_ENDPOINT_IP_WORKLOAD_CLUSTER: ${{ steps.get-control-plane-endpoint-ip-clusterctl-upgrade.outputs.control_plane_endpoint_ip_clusterctl_upgrade }}
-          NUTANIX_FAILURE_DOMAIN_1_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_1_PRISM_ELEMENT_NAME }}
-          NUTANIX_FAILURE_DOMAIN_1_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_1_SUBNET_NAME }}
-          NUTANIX_FAILURE_DOMAIN_2_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_2_PRISM_ELEMENT_NAME }}
-          NUTANIX_FAILURE_DOMAIN_2_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_2_SUBNET_NAME }}
-          NUTANIX_FAILURE_DOMAIN_3_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_3_PRISM_ELEMENT_NAME }}
-          NUTANIX_FAILURE_DOMAIN_3_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_3_SUBNET_NAME }}
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        control_plane_endpoint_ip="$(devbox run -- make nutanix-cp-endpoint-ip)"
+
+        echo "control_plane_endpoint_ip_clusterctl_upgrade=${control_plane_endpoint_ip}"
+        >> "${GITHUB_OUTPUT}"
+
+        '
+    - name: Check Control Plane endpoint IP for clusterctl upgrade
+      run: "if [[ -z \"${{ steps.get-control-plane-endpoint-ip-clusterctl-upgrade.outputs.control_plane_endpoint_ip_clusterctl_upgrade\
+        \ }}\" ]]; then\n  echo \"control_plane_endpoint_ip_clusterctl_upgrade is\
+        \ empty; cannot proceed with e2e tests\"\n  exit 1\nfi\n"
+    - name: Login to Internal Container Registry
+      uses: docker/login-action@v3
+      with:
+        registry: ${{ secrets.LOCAL_IMAGE_REGISTRY }}
+        username: ${{ secrets.LOCAL_IMAGE_REGISTRY_USERNAME }}
+        password: ${{ secrets.LOCAL_IMAGE_REGISTRY_TOKEN }}
+    - name: Test build
+      run: devbox run -- make ${{ inputs.make-target }} LABEL_FILTERS='${{ inputs.e2e-labels
+        }}'
+      env:
+        NUTANIX_USER: ${{ secrets.NUTANIX_USER }}
+        NUTANIX_PASSWORD: ${{ secrets.NUTANIX_PASSWORD }}
+        NUTANIX_ENDPOINT: ${{ secrets.NUTANIX_ENDPOINT }}
+        NUTANIX_GPU_PASSTHROUGH_NAME: ${{ vars.NUTANIX_GPU_PASSTHROUGH_NAME }}
+        NUTANIX_GPU_VIRTUAL_NAME: ${{ vars.NUTANIX_GPU_VIRTUAL_NAME }}
+        NUTANIX_PRISM_ELEMENT_CLUSTER_IP: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_IP
+          }}
+        NUTANIX_PRISM_ELEMENT_CLUSTER_USERNAME: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_USERNAME
+          }}
+        NUTANIX_PRISM_ELEMENT_CLUSTER_PASSWORD: ${{ secrets.NUTANIX_PRISM_ELEMENT_CLUSTER_PASSWORD
+          }}
+        LOCAL_IMAGE_REGISTRY: ${{ secrets.LOCAL_IMAGE_REGISTRY }}
+        WEBHOOK_KEY: ${{ secrets.WEBHOOK_KEY }}
+        WEBHOOK_CERT: ${{ secrets.WEBHOOK_CERT }}
+        WEBHOOK_CA: ${{ secrets.WEBHOOK_CA }}
+        NUTANIX_SSH_AUTHORIZED_KEY: ${{ secrets.NUTANIX_SSH_AUTHORIZED_KEY }}
+        NUTANIX_PRISM_ELEMENT_CLUSTER_NAME: ${{ steps.pe-params.outputs.NUTANIX_PRISM_ELEMENT_CLUSTER_NAME
+          }}
+        NUTANIX_SUBNET_NAME: ${{ steps.pe-params.outputs.NUTANIX_SUBNET_NAME }}
+        NUTANIX_ADDITIONAL_SUBNET_NAME: ${{ vars.NUTANIX_ADDITIONAL_SUBNET_NAME }}
+        NUTANIX_PROJECT_NAME: ${{ vars.NUTANIX_PROJECT_NAME }}
+        CONTROL_PLANE_ENDPOINT_IP: ${{ steps.get-control-plane-endpoint-ip.outputs.control_plane_endpoint_ip
+          }}
+        CONTROL_PLANE_ENDPOINT_IP_WORKLOAD_CLUSTER: ${{ steps.get-control-plane-endpoint-ip-clusterctl-upgrade.outputs.control_plane_endpoint_ip_clusterctl_upgrade
+          }}
+        NUTANIX_FAILURE_DOMAIN_1_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_1_PRISM_ELEMENT_NAME
+          }}
+        NUTANIX_FAILURE_DOMAIN_1_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_1_SUBNET_NAME
+          }}
+        NUTANIX_FAILURE_DOMAIN_2_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_2_PRISM_ELEMENT_NAME
+          }}
+        NUTANIX_FAILURE_DOMAIN_2_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_2_SUBNET_NAME
+          }}
+        NUTANIX_FAILURE_DOMAIN_3_PRISM_ELEMENT_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_3_PRISM_ELEMENT_NAME
+          }}
+        NUTANIX_FAILURE_DOMAIN_3_SUBNET_NAME: ${{ vars.NUTANIX_FAILURE_DOMAIN_3_SUBNET_NAME
+          }}
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
